# Generated by Django 2.2.13 on 2022-11-18 19:34

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_shownform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.IntegerField(unique=True)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'unknown')], help_text='Gender of the creature')),
                ('maturity', models.IntegerField(choices=[(0, 'adult'), (1, 'juvenile')], help_text='Maturity of the creature')),
                ('size', models.IntegerField(choices=[(0, '10-30cm'), (1, '30-50cm'), (2, '50-70cm'), (3, '70-100cm'), (4, '100-150cm'), (5, '>150cm'), (6, 'unknown')], help_text='Size of the creature')),
                ('misc_feature_description', models.CharField(blank=True, help_text='Feature description of the creature', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Bear',
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='building_status',
            field=models.CharField(blank=True, choices=[('A', '既有'), ('B', '新增'), ('C', '調查中'), ('D', '難以判定')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='cet_report_status',
            field=models.CharField(choices=[('A', '未回報'), ('O', '第一次電子郵件回報待回覆'), ('P', '第一次電子郵件回報已播電話追蹤'), ('Q', '第一次回電子郵件'), ('X', '第二次發電子郵件待回覆'), ('Y', '第二次發電子郵件已播電話追蹤'), ('Z', '第二次回電子郵件'), ('B', '已結案')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='cet_review_status',
            field=models.CharField(choices=[('A', '尚未審查'), ('O', '已審查-非遭遇事件'), ('P', '已審查-需補資訊'), ('Q', '已審查-待調查'), ('X', '已審查-已生成報告')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='highlight_category',
            field=models.CharField(blank=True, choices=[('A', '新物種移入'), ('B', '已知物種'), ('C', '不明物種移入')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='usage_status',
            field=models.CharField(blank=True, choices=[('A', '目擊'), ('B', '活動痕跡'), ('C', '其他遭遇'), ('D', '難以判定')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='RecycledCreature',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.creature',),
            managers=[
                ('recycle_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
