# Generated by Django 2.2.13 on 2022-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20221214_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shownform',
            name='human_hurt',
            field=models.BooleanField(blank=True, help_text='是否有人受傷或意外發生', null=True),
        ),
    ]
