# Generated by Django 2.2.13 on 2023-01-11 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20221214_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohshownevent',
            name='bear_attractor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '無'), (1, '自然食物資源'), (2, '動物屍體'), (3, '農作物'), (4, '家禽/畜'), (5, '蜂蜜'), (6, '垃圾/廚餘'), (7, '動物飼料'), (8, '人類食物'), (9, '其他')], help_text='附近可能吸引熊接近的物品', null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ohshownevent',
            name='ground_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '森林(天然林)'), (1, '森林(人工林)'), (2, '森林(次生林)'), (3, '溪流或河床'), (4, '住宅房舍附近'), (5, '遊憩區(包括山屋 / 營地週遭)'), (6, '道路(步道)'), (7, '道路(馬路)'), (8, '道路(林道)'), (9, '道路(產業道路)'), (10, '農牧用地(果園)'), (11, '農牧用地(菜園)'), (12, '農牧用地(休耕地)'), (13, '農牧用地(養蜂場)'), (14, '農牧用地(禽舍)'), (15, '農牧用地(豬舍)'), (16, '農牧用地(工寮或倉庫)'), (17, '其他')], help_text='土地類型', null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ohshownevent',
            name='vegetation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '闊葉林'), (1, '針葉林'), (2, '混合林'), (3, '灌叢'), (4, '草原'), (5, '竹林/箭竹林'), (6, '裸露地'), (7, '其他')], help_text='植被', null=True), blank=True, null=True, size=None),
        ),
    ]
