# Generated by Django 2.2.13 on 2023-02-08 08:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20230208_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceform',
            name='trace_type_desc',
        ),
        migrations.AddField(
            model_name='traceform',
            name='trace_type_text_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='痕跡類型-文字補充', null=True),
        ),
        migrations.AlterField(
            model_name='traceform',
            name='age_type',
            field=models.IntegerField(blank=True, choices=[(0, '新'), (1, '舊'), (2, '不清楚')], help_text='痕跡新舊類型', null=True),
        ),
    ]
