# Generated by Django 2.2.13 on 2023-03-15 08:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20230315_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='ohshown_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.OhshownEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shownform',
            name='ohshown_event',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.OhshownEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceform',
            name='ohshown_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.OhshownEvent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ohshownevent',
            name='prevent_ohshown_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '盡量結伴同行無'), (1, '輕聲走路'), (2, '必要時，沿途製造些聲響，如吹口哨、講話'), (3, '避免走夜路'), (4, '妥善收存食物、垃圾與廚餘'), (5, '看到熊在遠方時，人要輕聲離開現場'), (6, '單獨行動'), (7, '隨身攜帶哨子或鈴鐺'), (8, '攜帶防熊噴霧'), (9, '其他')], help_text='您知道以下哪些做法有助於減少遇到熊的機會，或避免不愉快地與熊相遇充', null=True), blank=True, null=True, size=None),
        ),
    ]
