# Generated by Django 2.2.13 on 2023-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20230315_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'unknown')], help_text='Gender of the creature', null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='maturity',
            field=models.IntegerField(blank=True, choices=[(0, 'adult'), (1, 'juvenile')], help_text='Maturity of the creature', null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, '10-30cm'), (1, '30-50cm'), (2, '50-70cm'), (3, '70-100cm'), (4, '100-150cm'), (5, '>150cm'), (6, 'unknown')], help_text='Size of the creature', null=True),
        ),
    ]
