# Generated by Django 2.2.13 on 2023-04-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20230412_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='ohshown_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to='api.OhshownEvent'),
        ),
        migrations.AlterField(
            model_name='shownform',
            name='ohshown_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_form', to='api.OhshownEvent'),
        ),
        migrations.AlterField(
            model_name='traceform',
            name='ohshown_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_form', to='api.OhshownEvent'),
        ),
    ]
